title: Ogma - Hub de tutos
description: "Plateforme de tutoriels pour reprendre le contrôle sur ta vie numérique. Sécurité, vie privée, outils open-source."
baseurl: "/ogma.github.io"
url: "https://6co-cp.github.io"

collections:
  tutoriels:
    output: true
    permalink: /:collection/:path/
