title: Ogma - Hub de tutos
description: "Plateforme de tutoriels pour reprendre le contrôle sur ta vie numérique. Sécurité, vie privée, outils open-source."
baseurl: "/"
url: "https://ogma-info.github.io"

collections:
  tutoriels:
    output: true
    permalink: /:collection/:path/
